version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: pg17
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER-pguser}
      POSTGRES_PASSWORD: ${DB_PASSWORD-pgpassword}
      POSTGRES_DB: ${DB_NAME-markopolo}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
